package_assets: always
embed_assets: on
s3_bucket: jammit-s3-testapp
s3_access_key_id: <%= ENV['S3_ACCESS_KEY_ID'] %>
s3_secret_access_key: <%= ENV['S3_SECRET_ACCESS_KEY'] %>
use_cloudfront: on
cloudfront_dist_id: EP4BTJ0LC2NN2
cloudfront_domain: d3ufgt52562mlv.cloudfront.net
#s3_cache_control: public, max-age=<%= 365 * 24 * 60 * 60 %>
#s3_cloudfront_host: <%= ENV['S3_CLOUDFRONT_HOST'] %>

s3_upload_files:
  - public/stylesheets/img/**

javascripts:
  application:
    - public/javascripts/application.js

stylesheets:
  common:
    - public/stylesheets/application.css
